ballerina-platform/module-ballerina-data.xmldata

ballerina/Dependencies.toml
gradle.properties

Update group and lang version

---

README.md
ballerina/build.gradle

Update build script and add badges to readme file

---

README.md

Correct codecov url

---

compiler-plugin/src/main/java/io/ballerina/lib/data/xmldata/compiler/XmldataRecordFieldValidator.java

Fixes: [#6296](https://github.com/ballerina-platform/ballerina-library/issues/6296)

Check module name when checking parse functions

---

ballerina/Dependencies.toml
gradle.properties

Update ballerina lang version

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

Fix workflow template links

---

compiler-plugin-test/src/test/java/io/ballerina/lib/data/xmldata/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/ballerina_sources/sample_package_10/Ballerina.toml
compiler-plugin-test/src/test/resources/ballerina_sources/sample_package_10/main.bal
compiler-plugin-test/src/test/resources/ballerina_sources/sample_package_10/modules/util/util.bal
compiler-plugin/src/main/java/io/ballerina/lib/data/xmldata/compiler/XmldataRecordFieldValidator.java

Fixes:  [#6498](https://github.com/ballerina-platform/ballerina-library/issues/6498)

Fix document lookup in compiler plugin

---

ballerina/Module.md
ballerina/Package.md

Fixes: [#6607](https://github.com/ballerina-platform/ballerina-library/issues/6607)

Add Module.md file to data.xmldata

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/tests/fromXml_test.bal
ballerina/tests/toXml_test.bal
compiler-plugin/src/main/java/io/ballerina/lib/data/xmldata/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/lib/data/xmldata/compiler/XmldataRecordFieldValidator.java
compiler-plugin/src/main/java/io/ballerina/lib/data/xmldata/compiler/objects/QualifiedName.java
native/src/main/java/io/ballerina/lib/data/xmldata/utils/DataUtils.java
native/src/main/java/io/ballerina/lib/data/xmldata/xml/QualifiedName.java
native/src/main/java/io/ballerina/lib/data/xmldata/xml/QualifiedNameMap.java
native/src/main/java/io/ballerina/lib/data/xmldata/xml/XmlParser.java

Fixes: [#6705](https://github.com/ballerina-platform/ballerina-library/issues/6705)

Handle attribute and element with same name in the same scope

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/tests/toXml_test.bal
native/src/main/java/io/ballerina/lib/data/xmldata/utils/DataUtils.java

Fixes: [#6744](https://github.com/ballerina-platform/ballerina-library/issues/6744)

Fix toXml failed when record field type is reference type and the referred type is not record type

---

ballerina/Dependencies.toml
gradle.properties

Update lang version

---

ballerina/Dependencies.toml
gradle.properties

Update io version

---

ballerina/Dependencies.toml
ballerina/tests/fromXml_test.bal
native/src/main/java/io/ballerina/lib/data/xmldata/xml/XmlParser.java

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6890

Fix CCE in arrays with refered types

---

gradle.properties

Change time and constraint timestamps

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties

Update 1.2.0 minor version

---

ballerina/Ballerina.toml
gradle.properties

Prepare for Update 12 release

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties

Update library timestamp dependencies

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/tests/toXml_test.bal
native/src/main/java/io/ballerina/lib/data/xmldata/utils/ToXmlUtils.java

Fixes https://github.com/ballerina-platform/ballerina-library/issues/6833

Fix `toXml` issues related to the rest type

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/build.gradle
ballerina/tests/xpathTest.bal
ballerina/tests/xpath_test.bal
ballerina/xpath_api.bal
build-config/resources/Ballerina.toml
compiler-plugin-test/src/test/java/io/ballerina/lib/data/xmldata/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/ballerina_sources/sample_package_14/Ballerina.toml
compiler-plugin-test/src/test/resources/ballerina_sources/sample_package_14/main.bal
compiler-plugin/src/main/java/io/ballerina/lib/data/xmldata/compiler/XmldataDiagnosticCodes.java
compiler-plugin/src/main/java/io/ballerina/lib/data/xmldata/compiler/XmldataRecordFieldValidator.java
gradle.properties
native/build.gradle
native/src/main/java/io/ballerina/lib/data/xmldata/xpath/ConvertibleBasicType.java
native/src/main/java/io/ballerina/lib/data/xmldata/xpath/InvalidQueryException.java
native/src/main/java/io/ballerina/lib/data/xmldata/xpath/ResultTypeMismatchException.java
native/src/main/java/io/ballerina/lib/data/xmldata/xpath/XPath.java
native/src/main/java/module-info.java
native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/data/xmldata-native/reflect-config.json

$subject
Part of:[#7748](https://github.com/ballerina-platform/ballerina-library/issues/7748)

XPath support for simple and sequence basic types types

---

ballerina/xpath_api.bal
gradle.properties

Fix typo in api doc

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/tests/fromXml_test.bal
gradle.properties
native/src/main/java/io/ballerina/lib/data/xmldata/FromString.java
native/src/main/java/io/ballerina/lib/data/xmldata/utils/DataUtils.java
native/src/main/java/io/ballerina/lib/data/xmldata/xml/XmlTraversal.java

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7942

Support XML type as a field type

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/xml_api.bal

Make validate isolated

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/xml_api.bal

[2201.11.x] Make validate isolated 
